version: '3.5'

services:
    php:
        build:
            context: docker/php
        env_file:
            - .env
        environment:
            XDEBUG_CONFIG: remote_host=${XDEBUG_HOST} remote_port=${XDEBUG_PORT} idekey=${XDEBUG_IDEKEY}
            PHP_IDE_CONFIG: serverName=${IDE_SERVER_NAME}
        volumes:
            - ~/.composer:/var/www/.composer
            - .:/var/www/html
            - shared-tmp:/tmp/ivory-google-map
        depends_on:
            - selenium-chrome
        links:
            - selenium-chrome:selenium-chrome

    selenium-chrome:
        image: selenium/standalone-chrome-debug
        ports:
            - "5900:5900"
        volumes:
            - shared-tmp:/tmp/ivory-google-map

volumes:
    shared-tmp:
